[General]
filedialog-path=@Variant(\0\0\0\x11\0\0\0\v/home/cnqso)
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x4\xbe\0\0\0\x36\0\0\t\xea\0\0\x5\x8a\0\0\x4\xbe\0\0\0\x36\0\0\t\xea\0\0\x5\x8a\0\0\0\0\0\0\0\0\n\0\0\0\x4\xbe\0\0\0\x36\0\0\t\xea\0\0\x5\x8a)

[FullScreen]
pos=@Point(882 1375)
screen=@Rect(0 0 2560 1440)
wide=false

[MainWindow]
QtStyle=System's default
adv-controls=0
bgSize=@Size(628 605)
pl-dock-status=false
playlist-visible=false
playlistSize=@Size(-1 -1)
status-bar-visible=false

[OpenDialog]
advanced=false
size=@Size(526 400)

[Preferences]
geometry="@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x3p\0\0\x1r\0\0\x6\x8e\0\0\x4,\0\0\x3p\0\0\x1r\0\0\x6\x8e\0\0\x4,\0\0\0\0\0\0\0\0\n\0\0\0\x3p\0\0\x1r\0\0\x6\x8e\0\0\x4,)"

[RecentsMRL]
list=file:///mnt/sdb/Media/Photos/2024/DCIM/108APPLE/IMG_8400.MOV, file:///mnt/sdb/Media/Photos/2024/DCIM/105APPLE/IMG_5273.MOV, file:///mnt/sdb/Media/Photos/2024/DCIM/105APPLE/IMG_5261.MOV, file:///mnt/sdb/Media/Photos/2024/DCIM/105APPLE/IMG_5259.MOV, file:///mnt/sdb/Media/Photos/2024/DCIM/105APPLE/IMG_5258.MOV, file:///mnt/sdb/Media/Photos/2024/DCIM/105APPLE/IMG_5255.MOV, file:///mnt/sdb/Media/Photos/2024/DCIM/105APPLE/IMG_5254.MOV, file:///mnt/sdb/Media/Photos/2024/DCIM/105APPLE/IMG_5243.MOV, file:///mnt/sdb/Media/Photos/2024/DCIM/106APPLE/IMG_6016.MOV, file:///mnt/sdb/Media/Photos/2024/DCIM/106APPLE/IMG_6004.MOV, file:///mnt/sdb/Media/Photos/2024/DCIM/106APPLE/IMG_6003.MOV, file:///mnt/sda/Godot/eee/ecg.20.04.23.blake.blossom.part.2.mp4, file:///mnt/sda/Godot/eee/shotherfirst.18.11.01.melody.marks.mp4, file:///mnt/sda/Godot/eee/0hy9j76kjkjmio61avnij_source.mp4, file:///mnt/sda/Godot/eee/2023-09-12_0hhtecj3mxau1rru1dohc_source.mp4, file:///mnt/sda/Godot/eee/Bella%20Blu%20%26%20Awlivv%2025.01.24%20Stepsis%20and%20BFF%20Creampie_Compressed.mp4, file:///mnt/sda/Godot/eee/INDIGO%20WHITE%20-%20LEWD%20GAME_%20BOOSETTE%20EDITION_Indigo%20White_hls_1080p.mp4, file:///mnt/sda/Godot/eee/Indigo_White_DaisyFairyAnal_Worship.mp4, file:///mnt/sda/Godot/eee/Indigo_White_DaisyFairyLewding_Your_Virgin_Bride.mp4, file:///mnt/sda/Godot/eee/835_gabbie_carter_full_hd_1080p_pf.mp4, file:///mnt/sda/Godot/eee/Dakota%20Tyler.mp4, file:///mnt/sda/Godot/eee/nym0199_melodymarks.mp4, file:///mnt/sda/Godot/eee/Charity%20Crawford%20-%20Charity%20Gives%20Back.mp4, file:///mnt/sda/Godot/eee/742666811505389569.mp4, file:///mnt/sda/Godot/eee/master.mp4, file:///mnt/sda/Godot/eee/0hy3acbt0lnj270mptq7k_source.mp4, file:///home/cnqso/Downloads/George%20Carrington%20MSc%20Ed%20on%20LinkedIn%20How%20Barts%20Demonstration%20of%20.mp4, file:///mnt/sda/Godot/eee/Alexia_Gold.mp4, file:///mnt/sda/Godot/eee/582_august_ames_full-hd_1080p.mp4, file:///mnt/sda/Godot/eee/BUNNY%20TIME%21%20-%20INDIGO%20WHITE_Indigo%20White_hls_1080p.mp4
times=0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 793513, 926917, 0, 1954590, 1549817, 760510, 122330, 1383775, 3418553, 4085684, 0, 2459685, 385970, 0, 736379, 0, 1915752, 1643375, 924919
